os: linux
language: go
group: stable
sudo: true
dist: trusty
go: 1.9
stages:
  - test
  - compile
  - name: image
    if: tag IS present
jobs:
  include:
  - stage: test
    go: 1.9
    script:
      - make test
  - stage: compile
    go: 1.9
    script:
      - make EXE=./dist/gendry/bin/gendry
      - tar -czvf ./dist/gendry-$(go env GOOS)-$(go env GOARCH).tar.gz -C ./dist/gendry ./
    deploy:
      skip_cleanup: true
      file_glob: true
      provider: releases
      api_key:
        secure: mTqpA9UBwRC1pPrI/M0zPwZHMNP/FFv7+oLhR2dQG/11yPdQdCH/UeOPNWBjDEbshyYh77O3of3lKvTucC4GaI6Cpgz4fEzrRhNtwnA6lF4Na6FNc/qwmF9sHCxxaxuADqDZq8R9MDrythEEFS3RCoS6eGDcd9S0ZLm0pjnwnm+UsC0nk+oLRnqf1ycxYmh6ZxRWPSv6fs9Pn+9TjULZHFX7wyPsc7P06ES+kRtA0kQI/brEf73Z1qF8KTzjHg4sRuorTi6sJbjlQe9rTudsXLe3z4w++ku/vXBTuUVRkHzr0kf/ApuKp2Agy6vHAnEL72LfYjIkA3XamZlpbLc/QNC07sNbCn8ita0a9wGgBwlalhAtbMfD4bYce4JYklkDQk7Q165h0iQL/gTxqfF/XhEu80Jh+XWGPF1480bujifZ9b4vVv3nqjjoJenkc4+vmvyHUjkaSpMjyFdxK6bm4qbrVmkIeqp67XQNVXtxYCi0oSzOtwl//hhy4ZMi9yzIirHw9Iy2XZp28ORK/8hsIG4/8thuoJkxQiS/KOC2swAku91xaOtXdcWE6ipnRm49r+GMrrCLSSP3u5NrbAAyoJlPsGEpUTR7EUIUQVgA5qBokipiP14bvVb0VibSUrm4I+XCU51LHjlhLobv8ofYrKgx9fVJKH00DFDQka2bBYM=
      file: "./dist/*.tar.gz"
      on:
        repo: dadleyy/gendry
        tags: true
  - stage: image
    go: 1.9
    script:
      - export IMAGE_TAG=$(git rev-parse --short HEAD)
      - export IMAGE_NAME=dadleyy/gendry:$IMAGE_TAG
      - export CONTAINER_NAME=gendry-$IMAGE_TAG
      - export ARTIFACT_FILE=gendry-$(go env GOOS)-$(go env GOARCH).tar.gz
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker pull golang:latest
      - wget https://github.com/dadleyy/gendry/releases/download/$TRAVIS_TAG/$ARTIFACT_FILE
      - mv $ARTIFACT_FILE ./gendry.tar.gz
      - docker build -t dadleyy/gendry:$IMAGE_TAG -f ./auto/docker/Dockerfile .
      - docker push dadleyy/gendry:$IMAGE_TAG
      - wget https://hyper-install.s3.amazonaws.com/hyper-linux-x86_64.tar.gz
      - tar xvzf hyper-linux-x86_64.tar.gz
      - ./hyper config --accesskey=$HYPER_ACCESS_KEY --secretkey=$HYPER_SECRET_KEY --default-region=us-west-1
      - ./hyper ps -a
      - ./hyper ps -a -f name=gendry-* -q | xargs ./hyper fip detach || echo ""
      - ./hyper ps -a -f name=gendry-* -q | xargs ./hyper stop || echo ""
      - ./hyper ps -a -f name=gendry-* -q | xargs ./hyper rm || echo ""
      - ./hyper run -d --name $CONTAINER_NAME -p 80:80 $IMAGE_NAME -address=0.0.0.0:80
      - ./hyper fip attach gendry-prod $CONTAINER_NAME
